<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
        <RootNamespace>GasMatic.Blazor.Wasm</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.7" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.7" />
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="8.0.0" />
        <PackageReference Include="SqliteWasmHelper" Version="1.2.0-beta-gf8e1db1f31"/>
    </ItemGroup>

    <ItemGroup>
        <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GasMatic.Blazor.Localization\GasMatic.Blazor.Localization.csproj" />
        <ProjectReference Include="..\GasMatic.Blazor.Wasm.Sqlite\GasMatic.Blazor.Wasm.Sqlite.csproj" />
        <ProjectReference Include="..\GasMatic.Components\GasMatic.Components.csproj" />
        <ProjectReference Include="..\GasMatic.Core\GasMatic.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="Pages\GasVolume\GasVolumeCalculator.razor"/>
        <_ContentIncludedByDefault Remove="Pages\GasVolume\GasVolumeHistory.razor"/>
        <_ContentIncludedByDefault Remove="Pages\Home.razor"/>
        <_ContentIncludedByDefault Remove="Shared\CustomInputText.razor"/>
        <_ContentIncludedByDefault Remove="wwwroot\sample-data\weather.json" />
        <_ContentIncludedByDefault Remove="Components\Shared\CultureSelect.razor" />
        <_ContentIncludedByDefault Remove="Components\Shared\CustomInputText.razor" />
        <_ContentIncludedByDefault Remove="Components\Shared\Error.razor" />
        <_ContentIncludedByDefault Remove="Components\Shared\TestErrorChildComponent.razor" />
        <_ContentIncludedByDefault Remove="Components\Layout\MainLayout.razor" />
        <_ContentIncludedByDefault Remove="Components\Layout\NavMenu.razor" />
        <_ContentIncludedByDefault Remove="Components\Pages\GasVolume\GasVolume.razor" />
        <_ContentIncludedByDefault Remove="Components\Pages\GasVolume\GasVolumeCalculator.razor" />
        <_ContentIncludedByDefault Remove="Components\Pages\GasVolume\GasVolumeHistory.razor" />
        <_ContentIncludedByDefault Remove="Components\Pages\Home.razor" />
        <_ContentIncludedByDefault Remove="Components\Pages\Settings.razor" />
        <_ContentIncludedByDefault Remove="Components\Pages\TestError.razor" />
        <_ContentIncludedByDefault Remove="wwwroot\scripts\culture.js" />
    </ItemGroup>

</Project>
