//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasMatic.Shared.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GasMatic.Mobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GasVolumeCalculatorTitle {
            get {
                return ResourceManager.GetString("GasVolumeCalculatorTitle", resourceCulture);
            }
        }
        
        internal static string NominalPipeSizeLabel {
            get {
                return ResourceManager.GetString("NominalPipeSizeLabel", resourceCulture);
            }
        }
        
        internal static string LengthLabel {
            get {
                return ResourceManager.GetString("LengthLabel", resourceCulture);
            }
        }
        
        internal static string PressureLabel {
            get {
                return ResourceManager.GetString("PressureLabel", resourceCulture);
            }
        }
        
        internal static string UseCustomPressureLabel {
            get {
                return ResourceManager.GetString("UseCustomPressureLabel", resourceCulture);
            }
        }
        
        internal static string CalculateButton {
            get {
                return ResourceManager.GetString("CalculateButton", resourceCulture);
            }
        }
        
        internal static string GasVolumeHistoryTitle {
            get {
                return ResourceManager.GetString("GasVolumeHistoryTitle", resourceCulture);
            }
        }
        
        internal static string GasVolumeLabel {
            get {
                return ResourceManager.GetString("GasVolumeLabel", resourceCulture);
            }
        }
        
        internal static string LengthPlaceholder {
            get {
                return ResourceManager.GetString("LengthPlaceholder", resourceCulture);
            }
        }
        
        internal static string PressurePlaceholder {
            get {
                return ResourceManager.GetString("PressurePlaceholder", resourceCulture);
            }
        }
        
        internal static string NominalPipeSizePicker {
            get {
                return ResourceManager.GetString("NominalPipeSizePicker", resourceCulture);
            }
        }
        
        internal static string PressurePicker {
            get {
                return ResourceManager.GetString("PressurePicker", resourceCulture);
            }
        }
        
        internal static string CalculatedDateLabel {
            get {
                return ResourceManager.GetString("CalculatedDateLabel", resourceCulture);
            }
        }
        
        internal static string GasVolumeCalculationsEmptyLabel {
            get {
                return ResourceManager.GetString("GasVolumeCalculationsEmptyLabel", resourceCulture);
            }
        }
        
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        internal static string EffectCalculatorTitle {
            get {
                return ResourceManager.GetString("EffectCalculatorTitle", resourceCulture);
            }
        }
        
        internal static string CalculateTab {
            get {
                return ResourceManager.GetString("CalculateTab", resourceCulture);
            }
        }
        
        internal static string HistoryTab {
            get {
                return ResourceManager.GetString("HistoryTab", resourceCulture);
            }
        }
        
        internal static string EffectHistoryTitle {
            get {
                return ResourceManager.GetString("EffectHistoryTitle", resourceCulture);
            }
        }
        
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        internal static string PreferencesLabel {
            get {
                return ResourceManager.GetString("PreferencesLabel", resourceCulture);
            }
        }
        
        internal static string DeleteAllDataLabel {
            get {
                return ResourceManager.GetString("DeleteAllDataLabel", resourceCulture);
            }
        }
        
        internal static string DeleteAllDataHint {
            get {
                return ResourceManager.GetString("DeleteAllDataHint", resourceCulture);
            }
        }
        
        internal static string NominalPipeSizeLinkLabel {
            get {
                return ResourceManager.GetString("NominalPipeSizeLinkLabel", resourceCulture);
            }
        }
        
        internal static string DeleteAllDataInfoLabel {
            get {
                return ResourceManager.GetString("DeleteAllDataInfoLabel", resourceCulture);
            }
        }
        
        internal static string DeleteAllDataSliderLabel {
            get {
                return ResourceManager.GetString("DeleteAllDataSliderLabel", resourceCulture);
            }
        }
        
        internal static string DeveloperLabel {
            get {
                return ResourceManager.GetString("DeveloperLabel", resourceCulture);
            }
        }
        
        internal static string ContactLabel {
            get {
                return ResourceManager.GetString("ContactLabel", resourceCulture);
            }
        }
        
        internal static string BrowserHint {
            get {
                return ResourceManager.GetString("BrowserHint", resourceCulture);
            }
        }
        
        internal static string EmailHint {
            get {
                return ResourceManager.GetString("EmailHint", resourceCulture);
            }
        }
        
        internal static string CreditsLabel {
            get {
                return ResourceManager.GetString("CreditsLabel", resourceCulture);
            }
        }
        
        internal static string DotNetTextCreditsLabel {
            get {
                return ResourceManager.GetString("DotNetTextCreditsLabel", resourceCulture);
            }
        }
        
        internal static string DotNetDetailCreditsLabel {
            get {
                return ResourceManager.GetString("DotNetDetailCreditsLabel", resourceCulture);
            }
        }
        
        internal static string DeleteAllDataSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteAllDataSuccessMessage", resourceCulture);
            }
        }
        
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        internal static string ChangeLanguageDialogMessage {
            get {
                return ResourceManager.GetString("ChangeLanguageDialogMessage", resourceCulture);
            }
        }
        
        internal static string ChangeLanguageSuccessMessage {
            get {
                return ResourceManager.GetString("ChangeLanguageSuccessMessage", resourceCulture);
            }
        }
        
        internal static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        internal static string BrowserFailedTitle {
            get {
                return ResourceManager.GetString("BrowserFailedTitle", resourceCulture);
            }
        }
        
        internal static string BrowserFailedMessage {
            get {
                return ResourceManager.GetString("BrowserFailedMessage", resourceCulture);
            }
        }
    }
}
